### ISSUE TITLE
How to use ls command for node

### ISSUE THREAD

**Issue by Kali95739** [author/shell#13]
How to use a shell command to run "ls -l" and also "mkdir test" for node

**Comment by Kali95739** [comment]
Also to run the program do I use it like node --experimental-module ?

**Comment by Kali95739** [comment]
@coreybutler

**Comment by Kali95739** [comment]
Also quick question is the shell.exec function the exact same as the browser shell.exec

**Comment by Kali95739** [comment]
Like for example I run this code

**Comment by Kali95739** [comment]
//index.mjs//
import { Shell, Command } from '@author.io/shell'
const shell = new Shell({
  name: 'mycli',
  trailer: [
    function () { console.log('Done!' ) }
  ],
  command: [{
    name: 'dir',
    handler () {
      console.log('ls -l')
    },
    // Subcommands
    commands: [{
      name: 'perm',
      description: 'Permissions',
      handler () {
        console.log('Display permissions for a directory.')
      }
    }]
  }]
})

// Execute the "dir" command
shell.exec('dir')

// Execute the "perm" subcommand
shell.exec('dir perm')

**Comment by Kali95739** [comment]
And it just returns with mycli not like it should where you say

**Comment by Kali95739** [comment]
Never does this: ls -l
Done!

**Comment by Kali95739** [comment]
Help would be good to get this working even in node please

**Comment by Kali95739** [comment]
@coreybutler

**Comment by coreybutler** [comment]
For future reference, please try to collapse this into a single commment.

> How to use a shell command to run "ls -l" and also "mkdir test" for node

This library is primarily for creating your own shell, with your own commands. You're still restricted to the capabilities of the runtime though. For example, if you wanted to have a command to run `ls -l`, it would look something like this in Node.js:

**mycli.js**
```javascript
import { execSync } from 'child_process'

const shell = new Shell({
  name: 'mycli',
  commands: [
    new Command({
      name: 'list',
      alias: 'l',
      handler (meta) {
        console.log(execSync('ls', ['-l']).toString())
      }
    })
  ]
})

shell.exec('list') // runs the `ls -l` command on the current working directory.
```

`node mycli.js` will run the script, but most people configure a package.json file to support a binary, i.e.:

**package.json (excerpt)**
```
{
  "bin": {
    "mycli": "./mycli.js"
  }
}
```

This allows you to `npm install -g`, then you can run `mycli <command>` (i.e. `mycli list`).

This same feature won't work in the browser because `ls -l` is not accessible from the browser. The shell library is not designed to replicate any OS shell commands, it's only designed to let users create their own shell applications.

---

> Also to run the program do I use it like node --experimental-module ?

You can specify flags like `--experimental-module` if you like.

---

> Also quick question is the shell.exec function the exact same as the browser shell.exec

I'm not sure I clearly understand the question. Browser's do not have a shell.exec, but I _think_ you're asking whether this library's `exec` method is the same between Node and the browser... in which case the answer is yes, they're the same. This shell library is runtime-agnostic, so the API is the same whether it's run in Node, Deno, the browser, etc.

---

_What I think you want is the following:_

```javascript
//index.mjs//
import { Shell, Command } from '@author.io/shell'
import { execSync } from 'child_process'

const shell = new Shell({
  name: 'mycli',
  trailer: [
    function () { console.log('Done!' ) }
  ],
  commands: [{
    name: 'dir',
    handler () {
      console.log(execSync('ls', ['-l']).toString())
    },
    // Subcommands
    commands: [{
      name: 'perm',
      description: 'Permissions',
      handler () {
        // ... figure out the permissions and console.log them
        console.log('Display permissions for a directory.')
      }
    }]
  }]
})

// Execute the "dir" command
shell.exec('dir')

// This should output the directory listing, then "Done!

// Execute the "perm" subcommand
// I wrapped it in a setTimeout because it runs faster than the console can output data.
setTimeout(function () {
  shell.exec('dir perm')
  // This just logs out "Display permissions for a directory.", then "Done!"
}, 2000)
```

---

> And it just returns with mycli not like it should where you say

This is because you had "command" instead of "command**s**" on line 8 of your original code. Correcting it outputs the following:

<img width="244" alt="image" src="https://user-images.githubusercontent.com/770982/194950170-3329ea35-8338-49ee-9768-bf44ac202dfc.png">
